import { FONT } from "./constants.js";

const S={
  page:{minHeight:"100vh",background:"#f5f3ef",fontFamily:FONT,padding:"max(16px, env(safe-area-inset-top)) 12px 80px",maxWidth:980,margin:"0 auto"},
  header:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:18,gap:8},
  logoRow:{display:"flex",alignItems:"center",gap:7,marginBottom:3},
  studioName:{fontSize:21,fontWeight:700,color:"#1e2e1e"},
  sub:{fontSize:11,color:"#a09080"},
  addBtn:{background:"#4a6a4a",color:"#fff",border:"none",borderRadius:9,padding:"9px 16px",fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:FONT,whiteSpace:"nowrap"},
  pillRow:{display:"flex",gap:7,marginBottom:16,flexWrap:"wrap"},
  pill:{border:"none",borderRadius:20,padding:"6px 14px",fontSize:12,cursor:"pointer",fontFamily:FONT},
  toolbar:{display:"flex",gap:10,marginBottom:18},
  searchBox:{background:"#fff",border:"1.5px solid #ddd",borderRadius:10,padding:"9px 12px",display:"flex",alignItems:"center",flex:1},
  searchInput:{border:"none",background:"transparent",fontSize:14,color:"#3a3a3a",width:"100%",fontFamily:FONT},
  grid:{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(255px,1fr))",gap:12},
  empty:{color:"#b0a090",fontSize:14,padding:"36px 0",textAlign:"center",gridColumn:"1/-1"},
  card:{background:"#fff",borderRadius:13,padding:"14px 14px 12px",border:"1px solid #e4e0d8",boxShadow:"0 2px 8px rgba(60,50,30,.06)",position:"relative"},
  cardTop:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:9,flexWrap:"wrap",gap:4},
  memberName:{fontSize:15,fontWeight:700,color:"#1e2e1e"},
  statusBadge:{display:"flex",alignItems:"center",fontSize:11,borderRadius:20,padding:"3px 8px",fontWeight:600},
  dateRow:{display:"flex",alignItems:"center",gap:7,marginBottom:10,flexWrap:"wrap"},
  dateLabel:{fontSize:10,color:"#b0a090"},
  dateVal:{fontSize:11,color:"#4a4a4a",fontWeight:600},
  dChip:{marginLeft:"auto",fontSize:11,fontWeight:700,borderRadius:7,padding:"3px 8px"},
  actions:{display:"flex",gap:5},
  detailBtn:{flex:1,background:"#eef4ee",color:"#2e6e44",border:"none",borderRadius:7,padding:"7px 0",fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:FONT},
  editBtn:{background:"#f0ece4",color:"#6a6050",border:"none",borderRadius:7,padding:"7px 9px",fontSize:11,cursor:"pointer",fontFamily:FONT},
  delBtn:{background:"#f5eeee",color:"#c97474",border:"none",borderRadius:7,padding:"7px 8px",fontSize:11,cursor:"pointer",fontFamily:FONT},
  navBtn:{background:"#fff",border:"1.5px solid #ddd",borderRadius:8,padding:"7px 11px",fontSize:13,color:"#4a4a4a",cursor:"pointer",fontFamily:FONT},
  overlay:{position:"fixed",inset:0,background:"rgba(40,35,25,.55)",backdropFilter:"blur(6px)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:100,padding:"16px"},
  modal:{background:"#fff",borderRadius:16,padding:"20px 16px 24px",width:"100%",maxWidth:520,boxShadow:"0 8px 40px rgba(40,35,25,.22)",maxHeight:"90vh",overflowY:"auto"},
  modalHead:{display:"flex",alignItems:"center",gap:9,marginBottom:14},
  modalTitle:{fontSize:16,fontWeight:700,color:"#1e2e1e"},
  fg:{marginBottom:12},
  lbl:{display:"block",fontSize:11,color:"#9a8e80",marginBottom:4,fontWeight:600},
  inp:{width:"100%",border:"1.5px solid #ddd",borderRadius:9,padding:"10px 11px",fontSize:14,color:"#3a3a3a",background:"#fafaf7",fontFamily:FONT},
  modalBtns:{display:"flex",gap:8,justifyContent:"flex-end",marginTop:10},
  cancelBtn:{background:"#f0ece4",color:"#9a8e80",border:"none",borderRadius:9,padding:"9px 16px",fontSize:13,cursor:"pointer",fontFamily:FONT},
  saveBtn:{background:"#4a6a4a",color:"#fff",border:"none",borderRadius:9,padding:"9px 20px",fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:FONT},
  stepper:{width:28,height:28,borderRadius:7,border:"1.5px solid #ddd",background:"#fafaf7",color:"#4a4a4a",fontSize:15,cursor:"pointer",fontFamily:FONT},
};

export default S;
